AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for backend and related functions"

Globals:
  Function:
    Timeout: 60
    Tracing: PassThrough

Parameters:
  STAGE:
    Type: String
  KEEPAAPI:
    Type: String
  TELEGRAMTOKEN:
    Type: String
  TELEGRAMCHATID:
    Type: String
  S3BUCKET:
    Type: String

Conditions:
  IsProd: !Equals [ !Ref STAGE, prd ]

Resources:
  GatherData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "ebay_fba_gather_${STAGE}"
      Handler: ebay_emails.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Environment:
        Variables:
          keepa_api: !Ref KEEPAAPI
          secrets_bucket: !Ref S3BUCKET
          SQS_QUEUE_URL: !GetAtt SQSQueue.QueueUrl
      Architectures: 
        - x86_64
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - sqs:SendMessage
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - !Sub "arn:aws:s3:::${S3BUCKET}"
              - !Sub "arn:aws:s3:::${S3BUCKET}/*"
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"

  ProcessEbay:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "ebay_fba_process_${STAGE}"
      Handler: process_ebay.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          telegram_token: !Ref TELEGRAMTOKEN
          telegram_chat_id: !Ref TELEGRAMCHATID
          SQS_QUEUE_URL: !GetAtt SQSQueue.QueueUrl
      Architectures: 
        - x86_64
      Events:
        ProcessEbayQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt SQSQueue.Arn
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "ebay_fba_queue_${STAGE}"
      VisibilityTimeout: 60


  DeleteMessageHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/telegram/
      FunctionName: !Sub "telegram_delete_handler_${STAGE}"
      Handler: delete_ebay_message.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          telegram_token: !Ref TELEGRAMTOKEN
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telegram
            Method: post

