AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for backend and related functions"

Globals:
  Function:
    Timeout: 60
    Tracing: PassThrough

Parameters:
  STAGE:
    Type: String
  KEEPAAPI:
    Type: String
  TELEGRAMTOKEN:
    Type: String
  CHATID:
    Type: String
  S3BUCKET:
    Type: String
  CLIENTID:
    Type: String
  CLIENTSECRET:
    Type: String
  REFRESHTOKEN:
    Type: String
  MERCHANTTOKEN:
    Type: String
  

Conditions:
  IsProd: !Equals [ !Ref STAGE, prd ]

Resources:
  MainHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "telegram_main_handler_${STAGE}"
      Handler: telegram_handler.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          telegram_token: !Ref TELEGRAMTOKEN
          chat_id: !Ref CHATID
          gather_data_function: !GetAtt GatherData.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /telegram
            Method: post
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt GatherData.Arn

  GatherData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "ebay_fba_gather_${STAGE}"
      Handler: ebay_emails.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Environment:
        Variables:
          keepa_api: !Ref KEEPAAPI
          secrets_bucket: !Ref S3BUCKET
          telegram_token: !Ref TELEGRAMTOKEN
          process_ebay_function: !GetAtt ProcessEbay.Arn
          client_id: !Ref CLIENTID
          client_secret: !Ref CLIENTSECRET
          refresh_token: !Ref REFRESHTOKEN
          merchant_token: !Ref MERCHANTTOKEN
      Architectures: 
        - x86_64
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - lambda:InvokeFunction
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
              - !Sub "arn:aws:s3:::${S3BUCKET}"
              - !Sub "arn:aws:s3:::${S3BUCKET}/*"
              - !GetAtt ProcessEbay.Arn

  ProcessEbay:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "ebay_fba_process_${STAGE}"
      Handler: process_ebay.lambda_handler
      Runtime: python3.11
      Timeout: 60
      Environment:
        Variables:
          telegram_token: !Ref TELEGRAMTOKEN
      Architectures: 
        - x86_64
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
